### ISSUE TITLE
Feature request: Wrapper of gulp command that reads gulpfile.wisp

### ISSUE THREAD

**Issue by ikeji** [birdduck/gulp-wisp#1]
Can you add wrapper command that uses gulpfile.wisp instead of gulpfile.js?

**Comment by crteal** [comment]
Such that you could write the example usage from the README as something like...

``` clojure
(let [wisp (requires "gulp-wisp")]
  (.task gulp
    "wisp"
    (fn []
      (.pipe
       (.pipe
         (.src gulp "./src/*.wisp")
         wisp)
       (.dest gulp "./lib")))))
```

in a file called `gulpfile.wisp`?

Would the new command exposed in `gulp-wisp` take the place of `gulp` in your workflow?

**Comment by ikeji** [comment]
Yes, also you can define macro for it.

```
(defmacro deftask [name deps & body]
  `(gulp.task (name (quote ~name)) ~deps (fn [] ~@body)))

(defmacro --> [src & pipes]
  (reduce
    (fn [form operation]
      (cons '.pipe
            (cons form (list operation))))
    src
    pipes))

(deftask default []
  (-->
    (.src gulp "./src/*.wisp")
    (wisp)
    (.dest gulp "./lib")))
```

For coffeescript they had coffee-gulp script for that use case. 
https://github.com/F1ow/coffee-gulp
(Now this module is obsolete because gulp supports coffeescript by default.)

**Comment by crteal** [comment]
Thanks for the example! I'll see what I can do...

**Comment by crteal** [comment]
It looks like things have changed substantially in the gulp ecosystem since coffee-gulp was authored. From my reading and debugging it appears that the simple approach from that module is now impossible given the gulp internals. To make a long story short Wisp needs to be added to [node-interpret](https://github.com/tkellen/node-interpret) to get the behavior you requested (sans macros). I have [opened a pull request](https://github.com/tkellen/node-interpret/pull/17) that will hopefully make that happen sooner rather than later.

**Comment by ikeji** [comment]
Thanks a lot!!!
That's best solution.

**Comment by crteal** [comment]
I'm happy to help, thanks for the idea @ikeji!
